[tool.poetry]
name = "sandbox"
version = "0.1.0"
description = "Playground for python and poetry"
authors = ["Jakub Slys <jakub@slys.dev>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
